version: '3.0'

services:
  grafana:
    container_name: 'grafana-logship-datasource'
    build:
      dockerfile: ./.container/Containerfile
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 2345:2345/tcp
    volumes:
      # - ./dist:/var/lib/grafana/plugins/logsink-logship-datasource
      - ./provisioning:/etc/grafana/provisioning
