version: '3.0'

services:
  grafana:
    container_name: 'grafana-logship-datasource'
    build:
      dockerfile: ./.config/Containerfile
      args:
        grafana_version: ${GRAFANA_VERSION:latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/logsink-logship-datasource
      # - ./provisioning:/etc/grafana/provisioning
