version: '3.0'

services:
  grafana:
    container_name: 'grafana-logship-datasource'
    build:
      context: ./.config
      args:
        grafana_version: latest
    ports:
      - 3000:3000/tcp
    network:
      - host
    volumes:
      - ./.container/dashboards:/var/lib/grafana/dashboards
      - ./dist:/var/lib/grafana/plugins/grafana-logship-datasource
      - ./.container/provisioning:/etc/grafana/provisioning