version: '3.0'

services:
  grafana:
    container_name: 'grafana-logship-datasource'
    build:
      dockerfile: ./.config/Containerfile
      args:
        grafana_version: latest
    ports:
      - 3000:3000
    # network_mode: host
    volumes:
      - ./.container/provisioning:/etc/grafana/provisioning
      - ./.container/dashboards:/var/lib/grafana/dashboards
      - ./dist:/var/lib/grafana/plugins/grafana-logship-datasource
