{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hosted Service Discovery",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "Linux.JournalD\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), arg_max(timestamp, ExtraData) by SYSLOG_IDENTIFIER, machine\r\n"
    }
   ]
  },
  {
   "title": "Running Agents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "Logship.Agent.Uptime\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, counter, machine\r\n"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "query": "Logship.Agent.Uptime\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize machine\r\n"
    }
   ]
  },
  {
   "title": "Container Discovery",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "Linux.JournalD\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), arg_max(timestamp, ExtraData) by SYSLOG_IDENTIFIER, machine\r\n"
    }
   ]
  }
 ]
}