{
 "title": "Database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Write Transaction Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "logship.data.keyvalue2.transaction.length_ms\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where type == 'write'\r\n| project timestamp, value, type\r\n"
    }
   ]
  },
  {
   "title": "Write Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "logship.data.keyvalue2.transaction.length_ms\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where type == 'write'\r\n| summarize count() by bin (timestamp, $__interval), type\r\n"
    }
   ]
  },
  {
   "title": "Read Transaction Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "logship.data.keyvalue2.transaction.length_ms\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where type == 'read'\r\n| summarize count() by bin(timestamp, $__timeInterval), type\r\n\r\n"
    }
   ]
  },
  {
   "title": "Read Transaction Timer (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "logship.data.keyvalue2.transaction.length_ms\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where type == 'read'\r\n| project timestamp, value, type\r\n"
    }
   ]
  }
 ]
}