apiVersion: 1
datasources:
  - name: Logship
    type: logship-datasource
    isDefault: true
    jsonData:
      clusterUrl: http://try.logship.ai:5000/
      dataConsistency: strongconsistency
      defaultEditorMode: raw