apiVersion: 1
datasources:
  - name: Logship
    uid: P474DFC22BB136045
    type: logship-datasource
    isDefault: true
    jsonData:
      clusterUrl: http://172.21.0.1:5000/
      username: default
    secureJsonData:
      pass: default