{
 "title": "Device Drilldown",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "Machine Name",
    "query": "System.Environment\n| where timestamp > ago(30d)\n| summarize machine\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Latest Machine Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "System.Environment\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| project timestamp, TickCount64\r\n"
    }
   ]
  },
  {
   "title": "Operating System Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "System.Environment\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize Platform = arg_max(timestamp, OSPlatform), Version = arg_max(timestamp, OSVersion), Is64BitOperatingSystem = arg_max(timestamp, Is64BitOperatingSystem)\r\n"
    }
   ]
  },
  {
   "title": "Process Working Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Process\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| project timestamp, WorkingSet = WorkingSet64, Name\r\n"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "Linux.JournalD\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| project timestamp, MESSAGE, ExtraData, SYSLOG_IDENTIFIER, level = case(\r\n  toint(PRIORITY) == 0, \"emerg\",\r\n  toint(PRIORITY) == 1, \"alert\",\r\n  toint(PRIORITY) == 2, \"critical\",\r\n  toint(PRIORITY) == 3, \"error\",\r\n  toint(PRIORITY) == 4, \"warning\",\r\n  toint(PRIORITY) == 5, \"notice\",\r\n  toint(PRIORITY) == 6, \"info\",\r\n  toint(PRIORITY) == 7, \"debug\",\r\n  \"unknown\"), SYSLOG_FACILITY, machine\r\n| order by timestamp desc\r\n| limit 1000\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "System.Process.Cpu\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"logship-1\"\r\n| summarize max(percentage) by bin(timestamp, $__interval * 6), executable\r\n"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Network.Interfaces\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| project timestamp, BytesSent, BytesReceived, Name\r\n"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Memory\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| project timestamp, FreeMemory\r\n"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "System.Memory\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize arg_max(timestamp, TotalMemory)\r\n"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "System.Network.Interfaces\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize arg_max(timestamp, OperationalStatus), Type = arg_max(timestamp, Type), PhysicalAddress = arg_max(timestamp, PhysicalAddress), SupportsMulticast = arg_max(timestamp, SupportsMulticast), IsReceiveOnly = arg_max(timestamp, IsReceiveOnly), SupportsIPv6 = arg_max(timestamp, SupportsIPv6), SupportsIPv4 = arg_max(timestamp, SupportsIPv4) by Name\r\n"
    }
   ]
  },
  {
   "title": "Port Usage by Process",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "query": "System.Process.Ports\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize Name = arg_max(timestamp, ProcessName), Type = arg_max(timestamp, PortType), LocalPort = arg_max(timestamp, LocalPort), RemotePort = arg_max(timestamp, RemotePort) by OwningPid\r\n| limit 100\r\n"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Storage\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize arg_max(timestamp, TotalFreespaceBytes) by Name\r\n"
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "System.Storage\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where machine == \"$machine\"\r\n| summarize size = arg_max(timestamp, TotalSizeBytes) by Name\r\n"
    }
   ]
  }
 ]
}