{
 "title": "Default Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage By Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Process.Memory\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(bytes) by bin(timestamp, $__timeInterval * 8), executable, machine\r\n"
    }
   ]
  },
  {
   "title": "Network Packet Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "System.Network.Interfaces\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where OperationalStatus == \"Up\"\r\n| summarize max(UnicastPacketsSent), max(IncomingPacketsDiscarded), max(OutgoingPacketsWithErrors), max(NonUnicastPacketsReceived), max(UnicastPacketsReceived), max(NonUnicastPacketsSent), max(IncomingPacketsWithErrors), max(IncomingUnknownProtocolPackets), max(OutgoingPacketsDiscarded) by bin(timestamp, $__timeInterval), machine, Name, Id"
    }
   ]
  },
  {
   "title": "CPU Usage By Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "System.Process.Cpu\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(percentage) by bin(timestamp, $__timeInterval * 8), executable, machine\r\n"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Memory\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(FreeMemory), max(TotalMemory) by bin(timestamp, $__timeInterval), machine\r\n"
    }
   ]
  },
  {
   "title": "Thread count by process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "System.Process.Threads\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, count, executable, machine\r\n| summarize max(count) by bin(timestamp, $__timeInterval * 8), machine, executable\r\n"
    }
   ]
  },
  {
   "title": "Machine Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "targets": [
    {
     "query": "System.Environment\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, TickCount64, machine, OSVersion\r\n\r\n"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Network.Interfaces\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| where OperationalStatus == \"Up\"\r\n| summarize max(BytesReceived), max(BytesSent) by bin(timestamp, $__timeInterval), machine, Id\r\n"
    }
   ]
  },
  {
   "title": "Available Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "System.Storage\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(AvailableFreespaceBytes) by bin(timestamp, $__timeInterval), Name, machine\r\n\r\n"
    }
   ]
  }
 ]
}