{
 "title": "Processes",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "processId",
    "query": "System.Process.Cpu\n| where timestamp > ago(1d)\n| summarize by executable"
   }
  ]
 },
 "panels": [
  {
   "title": "Thread Count Per Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "System.Process.Threads\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, count, executable, machine\r\n"
    }
   ]
  },
  {
   "title": "Memory Usage By Process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "System.Process.Memory\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, bytes, machine, executable"
    }
   ]
  },
  {
   "title": "CPU Usage By Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "System.Process.Cpu\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, percentage, executable, machine\r\n"
    }
   ]
  }
 ]
}