{
 "title": "Washington D.C. Metropolitan Transit Authority",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "PublicTransit.WMATA.Bus.Alerts\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), id = arg_max(timestamp, id), alert_informedEntity = arg_max(timestamp, alert_informedEntity), alert_headerText_translation = arg_max(timestamp, alert_headerText_translation) "
    },
    {
     "query": "PublicTransit.WMATA.Rail.Alerts\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), id = arg_max(timestamp, id), alert_informedEntity = arg_max(timestamp, alert_informedEntity), alert_headerText_translation = arg_max(timestamp, alert_headerText_translation) \r\n"
    }
   ]
  },
  {
   "title": "Latest bus locations",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "PublicTransit.WMATA.Bus.Positions\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), latitude = arg_max(timestamp, vehicle_position_latitude), longitude = arg_max(timestamp, vehicle_position_longitude), arg_max(timestamp, vehicle_trip_routeId), arg_max(timestamp, vehicle_timestamp) by vehicle_vehicle_id\r\n\r\n"
    }
   ]
  },
  {
   "title": "Latest Metro locations",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "PublicTransit.WMATA.Rail.Positions\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| summarize max(timestamp), latitude = arg_max(timestamp, vehicle_position_latitude), longitude = arg_max(timestamp, vehicle_position_longitude), arg_max(timestamp, vehicle_trip_routeId), arg_max(timestamp, vehicle_timestamp) by vehicle_vehicle_id\r\n\r\n"
    }
   ]
  },
  {
   "title": "WMATA Bus Heatmap",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "PublicTransit.WMATA.Bus.Positions\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project longitude = vehicle_position_longitude, latitude = vehicle_position_latitude\r\n"
    }
   ]
  },
  {
   "title": "WMATA Metro Heatmap",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "PublicTransit.WMATA.Rail.Positions\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project longitude = vehicle_position_longitude, latitude = vehicle_position_latitude\r\n"
    }
   ]
  }
 ]
}