{
 "title": "Search Executor Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming metrics by Account/Schema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "logship.service.metrics.inflow.schema\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, schema, value, account, machine\r\n| summarize sum(value) by bin(timestamp, $__interval), account, schema\r\n"
    }
   ]
  },
  {
   "title": "Local File count by schema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "logship.service.executor.local.schemas.files\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, schema, value, account, machine\r\n| summarize file_count = max(value) by bin(timestamp, $__interval), account, schema, machine\r\n"
    }
   ]
  },
  {
   "title": "Incoming Metrics By Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "logship.service.metrics.inflow.count\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, value, account, machine\r\n| summarize sum(value) by bin(timestamp, $__interval), account\r\n"
    }
   ]
  },
  {
   "title": "Local Schema Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "logship.service.executor.local.schemas.size_bytes\r\n| where timestamp > $__timeFrom()\r\n| where timestamp < $__timeTo()\r\n| project timestamp, schema, value, account, machine\r\n| summarize file_count = max(value) by bin(timestamp, $__interval), account, schema, machine\r\n"
    }
   ]
  }
 ]
}