ARG grafana_version=latest
ARG grafana_image=grafana-oss
ARG logship_grafana_datasource_version=0.0.24

FROM grafana/${grafana_image}:${grafana_version}
ARG logship_grafana_datasource_version
COPY ./provisioning /etc/grafana/provisioning
COPY ./dashboards /var/lib/grafana/dashboards

# Make it as simple as possible to access the grafana instance for development purposes
# Do NOT enable these settings in a public facing / production grafana instance
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Viewer"
ENV GF_VIEWERS_CAN_EDIT "true"
ENV GF_AUTH_ANONYMOUS_ENABLED "true"
ENV GF_AUTH_BASIC_ENABLED "true"

# Set development mode so plugins can be loaded without the need to sign
ENV GF_DEFAULT_APP_MODE "development"
ENV GF_INSTALL_PLUGINS "https://github.com/logsink/grafana-logship-datasource/releases/download/v$logship_grafana_datasource_version/logship-datasource-$logship_grafana_datasource_version.zip;logship-grafana-datasource"