ARG grafana_version=latest
ARG grafana_image=grafana-enterprise

FROM docker.io/debian:latest AS build-env
WORKDIR /tmp
# Replace shell with bash so we can source files
RUN rm /bin/sh \
  && ln -s /bin/bash /bin/sh
ENV NODE_VERSION "18.15.0"
ENV NVM_DIR /root/.nvm
ENV GO_VERSION 1.20.2
ENV GOPATH /opt/go
RUN apt-get update --fix-missing \
  && apt-get upgrade -y \
  && apt-get install -y bash build-essential git libssl-dev tar wget
RUN wget -q https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz \
  && tar -C /opt -xzf go$GO_VERSION.linux-amd64.tar.gz \
  && ln -s /opt/go/bin/go /bin/go \
  && ln -s /opt/go/bin/gofmt /bin/gofmt \
  && git clone https://github.com/magefile/mage \
  && cd mage \
  && go run bootstrap.go \
  && ln -s /opt/go/bin/mage /bin/mage \
  && mkdir -p $NVM_DIR \
  && wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash \
  && /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN . $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm alias default $NODE_VERSION \
  && npm install -g -D npm@latest yarn@latest \
  && yarn global add babel eslint eslint-webpack-plugin eslint-plugin-react-hooks react react-dom react-hooks typescript tslib webpack webpack-cli @grafana/data @grafana/e2e @grafana/eslint-config @grafana/runtime @grafana/ui @types/react @emotion/css \
  && rm -r /tmp/*

FROM build-env as build
WORKDIR /app
COPY . .
RUN yarn && yarn install && go mod tidy
RUN mage -v
RUN yarn build

FROM docker.io/grafana/${grafana_image}:${grafana_version} as app
COPY --from=build /app/dist /var/lib/grafana/plugins/logship-datasource
COPY provisioning /etc/grafana/provisioning
COPY dashboards /var/lib/grafana/dashboards

# Make it as simple as possible to access the grafana instance for development purposes
# Do NOT enable these settings in a public facing / production grafana instance
ENV GF_AUTH_ANONYMOUS_ORG_ROLE "Editor"
ENV GF_AUTH_ANONYMOUS_ENABLED "true"
ENV GF_AUTH_BASIC_ENABLED "true"
ENV GF_SECURITY_ADMIN_USER "lsadmin"
ENV GF_SECURITY_ADMIN_PASSWORD "relieve-motorist-pressure"

# Set development mode so plugins can be loaded without the need to sign
ENV GF_DEFAULT_APP_MODE "development"
# ENV GF_SERVER_HTTP_PORT 2345